name: Release to nuget.org

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build src --no-restore /p:Version=${{github.event.release.name}}
      
    - name: Test
      run: dotnet test src --no-build --verbosity normal

    - name: Package 
      run: dotnet pack src/NovoNordisk.OpenTelemetry.Exporter.Bifrost -c Release /p:ContinuousIntegrationBuild=true /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageVersion=${{github.event.release.name}} -o $GITHUB_WORKSPACE/release

    - name: Publish
      run: dotnet nuget push $GITHUB_WORKSPACE/release/NovoNordisk.OpenTelemetry.Exporter.Bifrost.${{github.event.release.name}}.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json
